Repository codestates-seb/seb40_main_035, pull requests merged in 2022-11, with the labels that each got.

#9 #8 fix: 게시글 patchDto 유효성 검증 변경 및 Custom Validator 추가
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticlePatchDto.java
  server/src/main/java/com/codestates/mainproject/validator/NotSpaceInteger.java
  server/src/main/java/com/codestates/mainproject/validator/NotSpaceIntegerValidator.java
Labels: Bug, Backend

#12 Dev be feat/issue#11
  README.md
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleDetailResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleInterestDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticlePatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticlePostDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleSkillDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/entity/Article.java
  server/src/main/java/com/codestates/mainproject/domain/article/entity/ArticleInterest.java
  server/src/main/java/com/codestates/mainproject/domain/article/entity/ArticleSkill.java
  server/src/main/java/com/codestates/mainproject/domain/article/mapper/ArticleMapper.java
  server/src/main/java/com/codestates/mainproject/domain/article/service/ArticleService.java
  server/src/main/java/com/codestates/mainproject/domain/hashtag/entity/Hashtag.java
  server/src/main/java/com/codestates/mainproject/domain/interest/controller/InterestController.java
  server/src/main/java/com/codestates/mainproject/domain/interest/dto/InterestPatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/interest/dto/InterestPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/interest/dto/InterestResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/interest/entity/Interest.java
  server/src/main/java/com/codestates/mainproject/domain/interest/mapper/InterestMapper.java
  server/src/main/java/com/codestates/mainproject/domain/interest/repository/InterestRepository.java
  server/src/main/java/com/codestates/mainproject/domain/interest/service/InterestService.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberDetailResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberInterestDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberSkillDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/codestates/mainproject/domain/member/entity/MemberInterest.java
  server/src/main/java/com/codestates/mainproject/domain/member/entity/MemberSkill.java
  server/src/main/java/com/codestates/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/mainproject/domain/skill/controller/SkillController.java
  server/src/main/java/com/codestates/mainproject/domain/skill/dto/SkillPatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/skill/dto/SkillPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/skill/dto/SkillResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/skill/entity/Skill.java
  server/src/main/java/com/codestates/mainproject/domain/skill/mapper/SkillMapper.java
  server/src/main/java/com/codestates/mainproject/domain/skill/repository/SkillRepository.java
  server/src/main/java/com/codestates/mainproject/domain/skill/service/SkillService.java
Labels: Backend, Feat

#15 Dev be test/issue#4
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/codestates/mainproject/domain/answer/dto/AnswerPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/answer/dto/AnswerResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleDetailResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleHashtagDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticlePatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticlePostDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/HeartDto.java
  server/src/main/java/com/codestates/mainproject/domain/comment/dto/CommentPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/hashtag/dto/HashtagPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberDetailResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/test/java/com/codestates/mainproject/domain/answer/controller/AnswerControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/article/controller/ArticleControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/comment/controller/CommentControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/hashtag/controller/HashtagControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/member/controller/MemberControllerTest.java
Labels: Backend, Test

#19 Dev be test/issue#14
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/overview.adoc
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleHashtagDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleInterestDto.java
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleSkillDto.java
  server/src/main/java/com/codestates/mainproject/domain/interest/controller/InterestController.java
  server/src/main/java/com/codestates/mainproject/domain/interest/dto/InterestPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberInterestDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberSkillDto.java
  server/src/main/java/com/codestates/mainproject/domain/skill/dto/SkillPostDto.java
  server/src/test/java/com/codestates/mainproject/domain/article/controller/ArticleControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/interest/controller/InterestControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/skill/controller/SkillControllerTest.java
Labels: Backend, Test

#21 api html생성
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/overview.adoc
  server/src/main/java/com/codestates/mainproject/domain/member/controller/MemberController.java
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/overview.html
Labels: Docs, Backend

#28 Dev be feat/issue#7
  server/src/main/java/com/codestates/mainproject/domain/article/controller/ArticleController.java
  server/src/main/java/com/codestates/mainproject/domain/article/service/ArticleService.java
  server/src/main/java/com/codestates/mainproject/domain/comment/entity/Comment.java
  server/src/main/java/com/codestates/mainproject/domain/member/entity/Member.java
  server/src/main/resources/application-server.yml
Labels: Backend, Feat

#29 Dev be feat: jwt 기능 구현#3
  server/build.gradle
  server/src/main/java/com/codestates/mainproject/converter/StringListConverter.java
  server/src/main/java/com/codestates/mainproject/domain/answer/entity/Answer.java
  server/src/main/java/com/codestates/mainproject/domain/hashtag/dto/HashtagPatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/LoginDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/codestates/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/mainproject/exception/BusinessLogicException.java
  server/src/main/java/com/codestates/mainproject/exception/ExceptionCode.java
  server/src/main/java/com/codestates/mainproject/security/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/mainproject/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/mainproject/security/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/codestates/mainproject/security/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/mainproject/security/auth/jwt/MemberDetails.java
  server/src/main/java/com/codestates/mainproject/security/auth/jwt/MemberDetailsService.java
  server/src/main/java/com/codestates/mainproject/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/mainproject/security/redis/RedisConfig.java
  server/src/main/java/com/codestates/mainproject/security/redis/RedisDto.java
  server/src/main/java/com/codestates/mainproject/security/response/ErrorResponse.java
  server/src/main/java/com/codestates/mainproject/security/response/TokenResponse.java
  server/src/main/java/com/codestates/mainproject/security/util/ErrorResponder.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: Backend

#30 Dev be feat/issue#13
  server/src/main/java/com/codestates/mainproject/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/mainproject/domain/answer/entity/Answer.java
  server/src/main/java/com/codestates/mainproject/domain/answer/service/AnswerService.java
  server/src/main/java/com/codestates/mainproject/domain/article/service/ArticleService.java
  server/src/main/java/com/codestates/mainproject/domain/comment/service/CommentService.java
  server/src/main/java/com/codestates/mainproject/domain/hashtag/service/HashtagService.java
  server/src/main/java/com/codestates/mainproject/domain/interest/service/InterestService.java
  server/src/main/java/com/codestates/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/mainproject/domain/skill/service/SkillService.java
  server/src/main/java/com/codestates/mainproject/exception/ExceptionCode.java
  server/src/main/java/com/codestates/mainproject/response/ErrorResponse.java
  server/src/main/java/com/codestates/mainproject/security/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/mainproject/security/util/ErrorResponder.java
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
  server/src/test/java/com/codestates/mainproject/domain/answer/controller/AnswerControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/comment/controller/CommentControllerTest.java
Labels: Backend, Feat

#26 feat: 게시글 카드 컴포넌트 구현
  client/src/assets/image/like.svg
  client/src/assets/image/views.svg
  client/src/components/ArticleCard.js
  client/src/pages/Main.js
  client/src/utils/dateFormat.js
Labels: Design, Frontend, Feat

#31 Feat: 제목 입력란 컴포넌트 구현
  client/src/assets/style/GlobalVariable.js
  client/src/components/InputTitle.js
Labels: Design, Frontend, Feat

#36 Feat: 인원 선택란 컴포넌트 구현
  client/src/atom/atom.js
  client/src/components/NumberSelect.js
Labels: Frontend, Feat

#44 Feat: 관심분야 보기란 컴포넌트 구현
  client/src/atom/atom.js
  client/src/components/InterestView.js
Labels: Frontend, Feat

#48 Feat: 프로필 기본 정보란 컴포넌트 구현
  client/src/assets/image/userAvatar.png
  client/src/atom/atom.js
  client/src/components/DefaultButton.js
  client/src/components/MiniButton.js
  client/src/components/ProfileCard.js
Labels: Design, Frontend, Feat

#49 Feat: 관심 분야 선택란 컴포넌트 구현
  client/src/atom/atom.js
  client/src/components/InterestSelect.js
Labels: Design, Frontend, Feat

#50 feat: 게시글 내용 input 컴포넌트 구현 완료
  client/src/atom/atom.js
  client/src/components/DefaultInput.js
  client/src/components/InputBody.js
Labels: Frontend, Feat

#52 Feat : 모집여부 토글스위치 구현
  client/src/components/SwitchToggle.js
Labels: Design, Frontend, Feat

#53 Feat: 기술스택 보기란 컴포넌트 구현
  client/src/atom/atom.js
  client/src/components/SkillStackView.js
Labels: Design, Frontend, Feat

#57 refactor: 기술스택 선택란 리팩토링
  client/src/atom/atom.js
  client/src/components/SkillStackSelect.js
Labels: Frontend, Refactor

#62 #58 feat: 스킬 종류 추가 및 전체 게시글 조회 반환값 수정
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/overview.adoc
  server/src/main/java/com/codestates/mainproject/domain/article/controller/ArticleController.java
  server/src/main/java/com/codestates/mainproject/domain/skill/dto/SkillPatchDto.java
  server/src/main/java/com/codestates/mainproject/domain/skill/dto/SkillPostDto.java
  server/src/main/java/com/codestates/mainproject/domain/skill/dto/SkillResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/skill/entity/Skill.java
  server/src/main/java/com/codestates/mainproject/domain/skill/service/SkillService.java
  server/src/main/java/com/codestates/mainproject/dto/MultiResponseDto.java
  server/src/main/resources/data.sql
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/overview.html
  server/src/test/java/com/codestates/mainproject/domain/article/controller/ArticleControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/codestates/mainproject/domain/skill/controller/SkillControllerTest.java
Labels: Docs, Backend, Test, Chore, Feat

#64 #63 fix: 마이페이지 작성글 목록 반환 수정 및 보기 권한 허용
  server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticleSimpleResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberDetailResponseDto.java
  server/src/main/java/com/codestates/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/codestates/mainproject/security/config/SecurityConfiguration.java
  server/src/main/resources/application-aws.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/codestates/mainproject/domain/member/controller/MemberControllerTest.java
Labels: Docs, Backend, Refactor, Test

#71 Feat: 메인 페이지 구현
  client/src/atom/atom.js
  client/src/components/ArticlesGrid.js
  client/src/components/CloseButton.js
  client/src/components/DefaultButton.js
  client/src/components/ExtendedButton.js
  client/src/components/Header.js
  client/src/components/ScrollTopButton.js
  client/src/components/SkillFilterSelector.js
  client/src/pages/Main.js
Labels: Frontend, Feat

#74 feat: 게시글 작성 페이지 구현
  client/package.json
  client/src/atom/atom.js
  client/src/components/BackButton.js
  client/src/components/Calendar.js
  client/src/components/Header.js
  client/src/components/InputBody.js
  client/src/components/InputHashTag.js
  client/src/components/InputTitle.js
  client/src/components/InterestSelect.js
  client/src/components/NumberSelect.js
  client/src/components/SkillStackSelect.js
  client/src/pages/ArticleWrite.js
  client/src/utils/getFormatDate.js
Labels: Frontend, Feat

#76 Feat : 프로필 상세보기 수정
  client/src/pages/Profile.js
Labels: Frontend, Feat

#79 Feat: 게시글 상세보기 페이지 구현
  client/src/App.js
  client/src/assets/style/GlobalVariable.js
  client/src/components/Comment.js
  client/src/components/InterestView.js
  client/src/components/Recomment.js
  client/src/components/SkillStackView.js
  client/src/components/SwitchToggle.js
  client/src/pages/ArticleDetail.js
Labels: Design, Frontend, Feat

#80 Feat : 로그인 모달 구현
  client/src/atom/atom.js
  client/src/components/BackButton.js
  client/src/components/Header.js
  client/src/images/github login.png
  client/src/images/google login.png
  client/src/images/kakao login.png
  client/src/pages/LogIn.js
Labels: Design, Frontend, Feat

#81 feat: 게시글 수정 페이지 구현
  client/src/atom/atom.js
  client/src/components/InputBody.js
  client/src/components/SwitchToggle.js
  client/src/pages/ArticleEdit.js
  client/src/pages/ArticleWrite.js
  client/src/pages/MyPage.js
  client/src/utils/dateFormat.js
  client/src/utils/getEditSkills.js
  client/src/utils/getFormatDate.js
  client/src/utils/getSkills.js
  client/src/utils/submitFormatDate.js
Labels: Frontend, Refactor, Feat
