Repository codestates-seb/seb40_main_035, pull requests merged in 2022-12, with the labels that each got.

#90 refactor: 기술스택 보기란 정보받기, 수정삭제 작성자만 보이도록 리팩토링
  client/src/atom/atom.js
  client/src/pages/ArticleDetail.js
  client/src/pages/Profile.js
  client/src/utils/getSkills.js
Labels: Frontend, Refactor

#92 Design: 아티클 카드 수정 및 그리드 적용
  client/src/components/ArticleCard.js
  client/src/pages/MyPage.js
  client/src/pages/Profile.js
  client/src/pages/SignUp.js
Labels: Design, Frontend

#88 Feat: 마이페이지 수정 페이지 구현
  client/src/atom/atom.js
  client/src/components/InterestSelect.js
  client/src/components/LevelSelect.js
  client/src/components/MiniButton.js
  client/src/components/SkillStackSelect.js
  client/src/pages/ArticleDetail.js
  client/src/pages/MyPageEdit.js
Labels: Frontend, Refactor, Feat

#96 Feat: 회원가입 페이지 내 깃허브 연동 기능 구현
  client/src/App.js
  client/src/atom/atom.js
  client/src/components/LineInput.js
  client/src/components/MiniButton.js
  client/src/pages/ReceiveGithub.js
  client/src/pages/SignUp.js
Labels: Frontend, Feat

#98 Feat: 토스트UI 뷰어 적용,SweetAlert2 라이브러리 적용
  client/package.json
  client/src/assets/toast.js
  client/src/components/ContentViewer.js
  client/src/components/LevelSelect.js
  client/src/pages/ArticleDetail.js
  client/src/pages/ArticleEdit.js
  client/src/pages/ArticleWrite.js
  client/src/pages/LogIn.js
  client/src/pages/MyPage.js
  client/src/pages/MyPageEdit.js
  client/src/pages/SignUp.js
Labels: Refactor

#103 Feat/#082 로그인 구현
  client/src/atom/atom.js
  client/src/components/Header.js
  client/src/pages/ArticleDetail.js
  client/src/pages/ArticleEdit.js
  client/src/pages/ArticleWrite.js
  client/src/pages/LogIn.js
  client/src/pages/MyPage.js
  client/src/pages/MyPageEdit.js
Labels: Frontend, Feat

#104 feat: 토스트 UI 사진 업로드 및 반응형 수정
  client/src/components/ContentViewer.js
  client/src/components/InputBody.js
Labels: Design, Frontend, Feat

#108 fix: 작성자만 버튼 보이기 기능 버그 수정 및 반응형 수정
  client/src/components/Header.js
  client/src/components/InputHashTag.js
  client/src/components/ProfileCard.js
  client/src/pages/ArticleDetail.js
  client/src/pages/ArticleEdit.js
  client/src/pages/ArticleWrite.js
  client/src/pages/MyPage.js
  client/src/pages/Profile.js
Labels: Bug, Design, Frontend, Feat

#109 Fix: 로그인 상태에 따른 로직 변경
  client/src/components/Comment.js
  client/src/components/ContentViewer.js
  client/src/components/SwitchToggle.js
  client/src/pages/ArticleDetail.js
Labels: Bug, Frontend

#110 Feat: 깃허브 소셜 로그인 기능 구현
  client/src/components/Header.js
  client/src/pages/LogIn.js
  client/src/pages/ReceiveGithub.js
  client/src/pages/SignUp.js
Labels: Frontend, Feat

#111 Feat/#107 로그인 버그 수정
  client/src/assets/style/GlobalStyle.js
  client/src/components/Header.js
  client/src/pages/LogIn.js
Labels: Bug, Design, Frontend

#112 feat : 엔터키로 로그인 구현
  client/src/pages/LogIn.js
Labels: Frontend, Feat

#114 Fix: 회원가입 유효성 검사 상태 버그 수정
  client/src/pages/SignUp.js
Labels: Bug, Frontend

#129 Disign : 캘린더 범위 선택 삭제 및 오늘 날짜 색 변경
  client/src/components/Calendar.js
Labels: Design

#134 Fix: 깃허브 로그인 후 로그인 모달 닫기
  client/src/App.js
  client/src/assets/toast.js
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: Bug, Frontend

#135 Fix: 메인 페이지 아티클 요청 개수 수정
  client/src/pages/Main.js
Labels: Bug, Frontend

#136 Dev be feat/#70
  server/src/main/java/com/codestates/mainproject/domain/article/service/ArticleService.java
  server/src/main/java/com/codestates/mainproject/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/mainproject/security/oauth2/OAuth2MemberSuccessHandler.java
Labels: Backend, Refactor

#130 feat: 게시글 작성/수정 페이지 유효성 검사 수정
  client/src/components/InputBody.js
  client/src/components/InputTitle.js
  client/src/pages/ArticleEdit.js
  client/src/pages/ArticleWrite.js
Labels: Bug, Frontend

#139 Fix: 회원가입 페이지 닉네임/비밀번호 확인 유효성 검사 수정
  client/src/pages/SignUp.js
Labels: Bug, Frontend

#141 fix: 회원가입 버튼 눌렀을 때, 상태 초기화
  client/src/components/Header.js
  client/src/pages/ArticleWrite.js
  client/src/pages/SignUp.js
Labels: Bug, Frontend, Refactor

#143 design: favicon, title 변경
  client/public/3355.png
  client/public/3355_logo.png
  client/public/index.html
Labels: Design, Frontend

#147 docs: readme 수정
  README.md
Labels: Docs

#148 fix: 오타수정
  server/src/main/java/com/codestates/mainproject/domain/answer/entity/Answer.java
Labels: Refactor
